### ISSUE TITLE
07 Form Update dependencies

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/react-typescript-samples#116]
Update dependencies and check if code is uptodate

**Comment by torres007** [comment]
Hi @brauliodiez , 

I'm having some trouble migrating from react-router 3 to 4. While some componets as <Link> has been directly moved to react-router-dom some others have been removed such as:

-  hashHistory
https://github.com/ReactTraining/react-router/issues/4752
- IndexRoute
https://github.com/ReactTraining/react-router/issues/4732

So it's needed to rethink the app to update.

What do you suggest to do?

BR.

Carlos.

**Comment by torres007** [comment]
Hi,

I have some doubts with the hashHistory refactor. In my PR I am using the global object history and it works but I am not sure if it's correct.

I think would be better to access using this.props.history in the child components but I have not found a way to do it. Any suggestion?

**Comment by arp82** [comment]
I do not know if it is applicable to this case without looking further into the code, but here is how I did it in a personal project, taking for example a Redux Action to delete one object from the collection in the Backend

```
export function postBoardGame(boardGame, onSuccessCallback) {
    const url = `${ROOT_URL}/${BOARD_GAMES_ENDPOINT}`;
    const promise = axios.post(url, boardGame).then(onSuccessCallback);

    return {
        type: POST_BOARD_GAME,
        payload: promise,
    };
}
```

Then when calling that action from the corresponding Container, I added a callback to navigate backwards using this.props.history. The code can be found below 
```
deleteBoardGame = () => {
        const {id} = this.props.match.params;
        this.props.deleteBoardGame(id, () => {
            this.props.history.push('/');
        });
    }
```
