### ISSUE TITLE
TS2315: Type 'Middleware' is not generic

### ISSUE THREAD

**Issue by arshdeep** [Lemoncode/react-typescript-samples#136]
I am getting an error while building "[09 Redux](https://github.com/Lemoncode/react-typescript-samples/tree/master/09%20Redux)" sample in the project.

ERROR in [at-loader] ./node_modules/redux-thunk/index.d.ts:14:84
    TS2315: Type 'Middleware' is not generic.

Any ideas how to resolve this?

**Comment by brauliodiez** [comment]
I think redux thunk had an issue on it's typings, try this on tsconfig:
"skipLibCheck": true

We have this sample updated on this repo:

https://github.com/Lemoncode/redux-by-sample/tree/master/04%20Thunk

**Comment by arshdeep** [comment]
Thanks a lot @brauliodiez
