### ISSUE TITLE
About page sample 07 ./src/index.tsx should be ./src/components/index.tsx

### ISSUE THREAD

**Issue by brendon-colburn** [Lemoncode/react-typescript-samples#167]
Hey I noticed that the index here is listed with the wrong folder structure.  It was pretty straight forward to just look at the repo attached and see which index you meant but it could be confusing for some people.  Really like going through these samples so far!

**Comment by brauliodiez** [comment]
Thanks a lot for notifying this, going to create a branch and fix it

**Comment by brauliodiez** [comment]
Fixed, please don't hesitate reporting more faults on the readme's it will help a lot other developers following the guides. Thanks
