### ISSUE TITLE
IE11 error in bundle.js by invalid character

### ISSUE THREAD

**Issue by Fiser12** [Lemoncode/react-typescript-samples#182]
I'm using this configuration of typescript and webpack for my project and I have a bug of invalid character in IE11 and I don't know how to solved. I publish in stackoverflow the bug. 

https://stackoverflow.com/questions/56803998/ie11-error-in-bundle-js-by-invalid-character

**Comment by brauliodiez** [comment]
Are you transpiling to ES5? webpack config:

```javascript
    rules: [
      {
        test: /\.(ts|tsx)$/,
        exclude: /node_modules/,
        loader: "awesome-typescript-loader",
        options: {
          useBabel: true,
          babelCore: "@babel/core" // needed for Babel v7
        }
      },
```

**Comment by Fiser12** [comment]
Yes I have the same block of code
