### ISSUE TITLE
Code cleanup study

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/react-typescript-samples#30]
Current sample code base needs a good cleanup, I propose @algil to create first a list of enhancements, then we can break / group them by issues and proceed with the cleanup task.

About the list to be generated, I would propose something like:

- Enhancementes that must be applied:

    - Field name FireValidationFieldValueChange: wrong name it just updates ui it should be FireFieldValueChange
    - Remove imports that are not being used (e.g. memberapi in reducers).
    - (...) <-- @algil to create the whole list

- Enhancements that needs discussion set an standard and then be implemented / set coding standard rule:

    - Imports, should we remove the "default" and use always {} ?
    - (...)

A later stage will be to configure tslinter

To complete this task you can answer in the task listing the enhancementes in a single comment.

**Comment by algil** [comment]
Sounds good. I will work on it

**Comment by brauliodiez** [comment]
Let's start giving here ideas, and then compile them:

Must change:

- FireValidationFieldVallueChange to FireFieldValueChange
- Remove unnceseary imports (e.g. memberapi on reducers).


To be discussed:

- Avoid export default
- Separate presentationales from container.
- Create a enum / const like class for actions types..

**Comment by algil** [comment]
I add more items to list.

**Must change:**

- FireValidationFieldVallueChange to FireFieldValueChange
- Remove unnecessary imports (e.g. memberapi on reducers).
- Unifying variable names in imports (e.g. Sometimes we write 'memberAPI' and in other cases we write 'MemberAPI'. In my opinion, in this case we should write in camelCase due to a new instance is created when it's exported. In other case should be in PascalCase.
- Change tabs to 2 spaces characters for indentation and reformat code. For this, I recommend using  tslint.json file.
- Fixing syntax of properties in several interfaces. Change ',' for ';' and putting in the end of the property name.

**To be discussed:**

Avoid export default and import classes with curly-bracket {}
Separate presentationales from container.
Create a enum / const like class for actions types..

**Comment by brauliodiez** [comment]
Lets start with the first two items in the list

Sent from my Windows Phone

-----Mensaje original-----
De: "Antonio L. Gil" <notifications@github.com>
Enviado: ‎19/‎03/‎2016 12:06
Para: "Lemoncode/react-typescript-samples" <react-typescript-samples@noreply.github.com>
CC: "Braulio Diez" <braulio.diez@gmail.com>
Asunto: Re: [react-typescript-samples] Code cleanup study (#30)

I add more items to list.
Must change:
FireValidationFieldVallueChange to FireFieldValueChange 
Remove unnecessary imports (e.g. memberapi on reducers). 
Unifying variable names in imports (e.g. Sometimes we write 'memberAPI' and in other cases we write 'MemberAPI'. In my opinion, in this case we should write in camelCase due to a new instance is created when it's exported. In other case should be in PascalCase. 
Change tabs to 2 spaces characters for indentation and reformat code. For this, I recommend using tslint.json file. 
Fixing syntax of properties in several interfaces. Change ',' for ';' and putting in the end of the property name. 
To be discussed:
Avoid export default and import classes with curly-bracket {}
Separate presentationales from container.
Create a enum / const like class for actions types..

**Comment by brauliodiez** [comment]
Take as well the one about using same names fornthe imports.

This three tasks are heavy because we need to propagate them to all the samples plus test that we havent broken anthing.

On the other Hand it will enhance code readibility

Sent from my Windows Phone

-----Mensaje original-----
De: "braulio.diez@gmail.com" <braulio.diez@gmail.com>
Enviado: ‎19/‎03/‎2016 12:27
Para: "Lemoncode/react-typescript-samples" <reply@reply.github.com>; "Lemoncode/react-typescript-samples" <react-typescript-samples@noreply.github.com>
Asunto: RE: [react-typescript-samples] Code cleanup study (#30)

Lets start with the first two items in the list

Sent from my Windows Phone


De: Antonio L. Gil
Enviado: ‎19/‎03/‎2016 12:06
Para: Lemoncode/react-typescript-samples
CC: Braulio Diez
Asunto: Re: [react-typescript-samples] Code cleanup study (#30)


I add more items to list.
Must change:
FireValidationFieldVallueChange to FireFieldValueChange 
Remove unnecessary imports (e.g. memberapi on reducers). 
Unifying variable names in imports (e.g. Sometimes we write 'memberAPI' and in other cases we write 'MemberAPI'. In my opinion, in this case we should write in camelCase due to a new instance is created when it's exported. In other case should be in PascalCase. 
Change tabs to 2 spaces characters for indentation and reformat code. For this, I recommend using tslint.json file. 
Fixing syntax of properties in several interfaces. Change ',' for ';' and putting in the end of the property name. 
To be discussed:
Avoid export default and import classes with curly-bracket {}
Separate presentationales from container.
Create a enum / const like class for actions types..
