### ISSUE TITLE
Sample 05 should have constructor init in the member Entity

### ISSUE THREAD

**Issue by tomas-ortega** [Lemoncode/react-typescript-samples#4]
Member Entity it's missing in constructor, maybe need initialize in the constructor the id by -1.
This have been fix in sample 07 and not in sample 05
`constructor() {
    this.id = -1;
    this.login = "";
    this.avatar_url = "";
  }`

**Comment by algil** [comment]
I have a fork of the repository and I'm working on it. Soon I will open a pull request.

**Comment by brauliodiez** [comment]
@algil, accepted, reviewed and merge, good stuff, congrats.

**Comment by algil** [comment]
Thanks! :)
