### ISSUE TITLE
About page sample 03 Navigation

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/react-typescript-samples#40]
_Proposal ( @Nasdan to complete it):_

# 03 Navigation

This sample takes as starting point sample "02 Components".

We are adding page navigation to this project:

- We have added two pages (about, members).
- The user can navigate by cliking on links in a common navbar.

We are using react-router for the navigation support.

In order to launch this project, follow this steps 

 TODO: Add all the steps here, npm install... 
npm start

Then open your browser and navigate to: http://localhost:8080

**Highlights**

The most interesting parts worth to take a look:

- index.ts: routes configuration.

- header.tsx: navigation links.

- app.tsx: header + page container.

- aboutPage.tsx / members.tsx: pages.

**Comment by Nasdan** [comment]
@brauliodiez Do you think it's necessary add steps to install?
