### ISSUE TITLE
Call for contributors

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/react-typescript-samples#62]
Some months ago this project started as something internal... _let's create some simple samples that cover react / redux / typescript scenarios that could serve as a guidance and reference in the future_... now, we and other developers are using this repo as quick by sample guidance. We keep on adding more samples to it, but we have found that older samples need some updates / refactoring. 

Tasks that we are planning:
- Replace tsd and use typings on each sample.
- Add better naming to actions.
- Add a readme.md to each of the sample (explaining the sample and include an step by step guide to create them from default).
- Better use of imports, casing and other details (code quality).
- Introduce ts-linter.
- Add more samples.
- (...).

Are you interested in contributing into this project? If that's the case don't hesitate contacting us.

**Comment by linuxonrails** [comment]
I can contribute!

**Comment by brauliodiez** [comment]
You are more than welcome, once we have react-samples and redux-samples ready we can start applying the same update changes to this project (now is a bit outdated).

If you want to get started you can start with sample '00 Boilerplate' and sample '01 Hello React', updating to typescript 2.0 + type definitions, adding stateless components where applies...

I'm going to add you as team meber and assign you issues.

**Comment by stak99** [comment]
Is there anything you guys need, so I can contribute something.

**Comment by brauliodiez** [comment]
Great @stak99, we are now in the process of updating the samples to latest version of the libraries, @Nasdan can give you an entry point on where is the latest sample updated, on the other hand we are translating the step by step readme to other languages (e.g. spanish, it could be german, or whatever you feel comfortable).

**Comment by Nasdan** [comment]
The last sample that I update was `10 SpinnerAsync`.

The workflow to update a sample is:

- Start from previous refactored sample code.
- Create a README.md documenting step by step the changes that we are going to do in sample. (take a look how we are documenting other READMEs)
- Update About page content with the highlight of changes for sample.
- Install necessary libraries and change the code while documenting step by step README.

**Comment by praveen612** [comment]
I would like to contribute. I started to work on typescript recently and I think I can do some updating/refactoring/readme

**Comment by brauliodiez** [comment]
That's great @praveen612 to get started I would recommend you going through the readme, follow them step by step and for sure you will pinpoint typos, errors in code and things that can be enhanced, provide a PR per sample so it's easier to reivew. Thanks in advance

**Comment by brauliodiez** [comment]
@praveen612 another good entry point can be updating JQuery version (github is warning that we are using an old one that contains vulnerabities and ensure that the samples are still working)

**Comment by brauliodiez** [comment]
Hello @praveen612 Jquery issue has been assigned to another mate, readme review and enhancements are more than welcome
