### ISSUE TITLE
Avoid webpack global install, use npm start

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/react-typescript-samples#67]
Let's avoid npm -g installs whenver is possible.

We should in all projects:

```
npm install webpack webpack-dev-server --save
```

And add an start script to package json

```
"scripts": {
    "start": "webpack",    
  },
```

By doing this we can just execute from command line:

```
npm start
```

Add this change in all samples, then update the global readme.md

**Comment by Nasdan** [comment]
We have webpack and webpack-dev-server installed locally.
And we are using:

```
"scripts": {
    "start": "webpack-dev-server",    
  },
```

Do you mean add new command to build sample? like:

```
"scripts": {
    "start": "webpack-dev-server",
    "build": "webpack"
  },
```
And run `npm run build` ?
