### ISSUE TITLE
Remove hack, canot use statelessComponent

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/react-typescript-samples#7]
Right now on the definition of 

`class MemberPage extends React.Component<Props, {}> {`

We are using React.Component, we should be using React.StatelessComponent, if we make this change we get an error, we had to rollback to React.Component, and add an ugly hack when gluing the reducer:

```

// TODO: Hack to bypass the issue when declaring StateLessComponent
// Pending research here
var nonTypedMemberPage : any = MemberPage;

const ContainerMemberPage = connect(
                                   mapStateToProps
                                  ,mapDispatchToProps
                                )(nonTypedMemberPage)

```

We need to unsderstand what's going on here and how this could be fixed, found in stackoverflow that we should upgrade to typescript 1.8 in order to fix that done but no luck, maybe is just the tsd that is not well defined.

**Comment by Nasdan** [comment]
This issue was resolved in #8 Redux support. Before that is not needed.
