### ISSUE TITLE
Update sample  02 Components

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/react-typescript-samples#78]
UPgrade to typescript 2.0, update libraries to latest version, remove typings, review set state and other pitfalls.

No need for readme.md, just a good review and get all uptodate and remove errors.

**Comment by datencia** [comment]
On it!

**Comment by datencia** [comment]
what do you mean by "review set state" ? convert components to stateless ?

**Comment by brauliodiez** [comment]
We are not setting the state in the right way in most of the samples, we are not using setState in the right way
